### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by srl295** [bus1/cabuild#3]
on windows-latest:

```
Get-Command: /home/runner/work/_temp/436bd9a6-7eba-4ca0-9b04-c5ec22ddefb5.ps1:5
…
 $vswhere = Get-Command 'vswhere'
…
 The term 'vswhere' is not recognized as a name of a cmdlet, function …
```

-----

```yaml
jobs:
  meson-msvc:
    runs-on: ubuntu-latest
    # HT: https://dvdhrm.github.io/2021/04/21/meson-msvc-github-actions/
    name: Meson MSVC
    strategy:
      matrix:
        os:
        # - windows-2016
        - windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Dependencies
        run: pip install meson ninja
      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
```
